### ISSUE TITLE
error en linux 

### ISSUE THREAD

**Issue by maicolasad** [GataNina-Li/GataBotLite-MD#14]
Me imagino que también funciona en Linux.

pero me sale un error AHI ESTA

events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at process.target._send (internal/child_process.js:807:20)
    at process.target.send (internal/child_process.js:678:19)
    at sendHelper (internal/cluster/utils.js:26:15)
    at send (internal/cluster/child.js:193:10)
    at EventEmitter.cluster._setupWorker (internal/cluster/child.js:46:3)
    at initializeClusterIPC (internal/bootstrap/pre_execution.js:342:13)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:65:3)
    at internal/main/run_main_module.js:7:1
Emitted 'error' event on Worker instance at:
    at process.<anonymous> (internal/cluster/worker.js:29:12)
    at process.emit (events.js:314:20)
    at internal/child_process.js:811:39
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}

**Comment by maicolasad** [comment]
Me gustaría usarlo en Linux

**Comment by maicolasad** [comment]
Hola
